### PR TITLE
Updated dependencies and README

### PR DESCRIPTION
**Pull request by russellwhitaker**
I'm submitting this before work on the file uploader component.

### CODE REVIEW

**Comment by mhjort** [comment]
Cool. Have you checked that Leiningen plugin (both update & install) works properly after these version updates? Leiningen uberjar contains already some cheshire dependencies and I have had problems with that in the past.

**Comment by russellwhitaker** [comment]
Hi @mhjort I'd tested the library and lein plugin locally after installing jar files to my local `~/.m2` repository and sourcing from there after `lein install` and _thought_ I'd bumped the plugin in version in test. I checked again, and it looks like I'd not done the local plugin version bump, so I tested again, this time correcting that oversight. Actually, I was able to run the library fine with Cheshire versions 5.5.0, 5.6.0, 5.6.1, 5.6.2, and 5.6.3, but I *did* have failures with updating the Jackson XML lib versions, so I reverted those. I'll be pushing a corrected PR after I note this here.

**Comment by mhjort** [comment]
Great! Thanks for putting the effort on testing the dependencies. I appreciate that you fixed the language in README. My mother language is Finnish which does not even have a concept of articles like a, an and the. So for me it is way too easy to forget them when I write something. 

Could you do small rebase to git history of this PR before I merge. Like one commit for README update, one for updating the dependencies, and then one for bumping the release number of this tool. After that I can merge and deploy new versions to clojars.

**Comment by russellwhitaker** [comment]
I'm not sure how I could `git rebase` to break out these changes to reflect these separate concerns, given the way the changes were actually applied. Maybe I'm misunderstanding the request, can you please explain?

**Comment by mhjort** [comment]
Sorry. You are right. Rebase won't work in this case. I meant that you can do `git reset` (soft one) and then split the PR to these commits. However, this is a minor detail just to keep git history as tidy as possible. If you don't want spend extra time for this I can merge this as is?

**Comment by russellwhitaker** [comment]
If you don't mind merging as-is on this first PR, I'd be greatly appreciative, and will make sure that all subsequent pull requests I make conform to this preference, thanks!

**Comment by mhjort** [comment]
Yes. No problem. I just merged the PR and deployed new versions to clojars.

**Pull request merged**
